### ISSUE TITLE
Unreliable energy network behaviour in conjunction with Integrated Tunnels

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [KingLemming/1.16#22]
**Minecraft**: 1.16.5
**Thermal Expansion**: 1.16.3-1.1.6
**Forge**: 36.0.45

I've been trying to set up a very basic energy transport system for my Thermal setup using Integrated Dynamics / Tunnels,
and while doing so found some inconsistent or at least "quirky" behaviour (see https://github.com/CyclopsMC/IntegratedDynamics/issues/996) between the way these two systems interact, most notably:

- ID fails when trying to pull energy from a dynamo if a machine starts requesting energy after it has fully filled up (https://github.com/CyclopsMC/IntegratedDynamics/issues/996#issuecomment-790941376),
- and Thermal Energy Cells need to be set to **in/out** explicitly in order to allow extracting energy using an Energy Importer (https://github.com/CyclopsMC/IntegratedDynamics/issues/996#issuecomment-788088688).

As I said in the original issue, I'm not entirely certain on which side this regression (compared to 1.12 behaviour) lies here, and Ruben wasn't able to debug this further due to not being able to load Thermal into his dev environment, so I figured I'd also relay this here.

**Comment by KingLemming** [comment]
So...energy in Forge is push-based, not pull-based. I suspect therein lies the issue.

Machines receive energy. They never ask for it. I don't know Integrated Dynamics does to attempt to hack this into a pull-based system, but it just isn't that.

Nothing about RF (or FE) is really designed to have things *extract* energy because that is a far less computationally efficient way to handle energy transfer.

ID fails when trying to pull energy because it literally can't - the blocks don't support it and will not. They are designed to push. The fact that the Cell is somehow allowing it in I/O mode is an issue, but the issue there is active extraction being allowed in any way.

**Comment by MaxNeedsSnacks** [comment]
Closing because the issue on ID's side has also been closed, thanks for the input!
